### ISSUE TITLE
Общий дизайн интерфейса

### ISSUE THREAD

**Issue by MPStudent** [gsom95/VerySecretIpovsProject#10]
Необходимо описать общий концепт интерфейса игры (внешний вид элементов и их позиционирование) и предоставить эскизы вашему коллеге timon056, чтобы он мог по ним разработать статичный интерфейс. Прошу учитывать возможности выбранных при разработке инструментов и не добавлять этих ваших дизайнерский хитрых градиентов и т.д. Спасибо:)

**Comment by HelloV** [comment]
**Сделано**
commit ddff727b694ca33e6e87a3143a8a0a4b32ef0fce, 7db340a3d4af7826e02002be1d09ac8b1d99288a
