### ISSUE TITLE
Руководство оператора (Артём)

### ISSUE THREAD

**Issue by HelloV** [gsom95/VerySecretIpovsProject#17]
Написать, если ещё не написано, руководство оператора, как мы писали на бакалаврскую работу
Побольше интересных картинок и пояснений игровых ситуаций.

**Comment by timon056** [comment]
Готово
[Руководство оператора.pdf](https://github.com/gsom95/VerySecretIpovsProject/files/1037645/default.pdf)
[Руководство оператора.docx](https://github.com/gsom95/VerySecretIpovsProject/files/1037646/default.docx)
