### ISSUE TITLE
Создание дизайна танков и поля

### ISSUE THREAD

**Issue by MPStudent** [gsom95/VerySecretIpovsProject#5]
Разработать дизайн танков 3 разных типов, учесть различия между танками разных сторон. Продумать общий вид поля и размещение основных элементов управления. По результатам работы предоставить файлы изображений и общие эскизы.

**Comment by HelloV** [comment]
Дизайн создан
Исходники зафиксированы и выгружены в удалённый репозиторий
commit 7073a9ff4d7e5ed3c847665ca135a077ee2b208e
